from pathlib import Path
p = Path('/home/ubuntu/lumin-candles-store/client/src/pages/Home.tsx')
s = p.read_text()
s = s.replace('<button className="request-submit" onClick={startRequest}>ابحث عن الأقرب <ArrowLeft size={17} /></button>', '<button className={`request-submit ${isSearching ? "is-searching" : ""}`} onClick={startRequest} disabled={isSearching}>{isSearching ? <><span className="button-spinner" /> جارٍ البحث عن الأقرب...</> : <>ابحث عن الأقرب <ArrowLeft size={17} /></>}</button>', 1)
s = s.replace('<div className="map-panel"><div className="map-toolbar">', '<div className={`map-panel ${isSearching ? "map-is-searching" : ""}`}><div className="map-search-status">{isSearching && <><span className="status-loader" /> نجدة تبحث عن مقدمي الخدمة حولك...</>}</div><div className="map-toolbar">', 1)
p.write_text(s)
css = Path('/home/ubuntu/lumin-candles-store/client/src/index.css')
s = css.read_text()
s += '''\n.request-submit:disabled { cursor: wait; opacity: .92; }.request-submit.is-searching { background: #294b39; }.button-spinner, .status-loader { display: inline-block; height: 13px; width: 13px; border: 2px solid rgba(203,242,59,.32); border-top-color: var(--lime); border-radius: 999px; animation: spin .75s linear infinite; }.map-panel { position: relative; }.map-search-status { position: absolute; top: 43px; right: 14px; left: 14px; z-index: 4; display: flex; min-height: 30px; align-items: center; justify-content: center; gap: 7px; border: 1px solid rgba(155,193,111,.55); border-radius: 8px; background: rgba(247,252,248,.94); color: #5e7d54; font-size: 9px; box-shadow: 0 6px 14px rgba(48,82,49,.12); animation: searchStatusIn .2s ease-out; }.map-search-status:empty { display: none; }.map-is-searching .fake-map::before { animation: mapSweep 1.2s ease-in-out infinite alternate; }.map-is-searching .map-pulse { animation: pulse 1s ease-in-out infinite; }.map-is-searching .map-pin { animation: pinPulse 1s ease-in-out infinite; }.map-is-searching .map-pin:nth-of-type(2) { animation-delay: .12s; }.map-is-searching .map-pin:nth-of-type(3) { animation-delay: .24s; }.map-is-searching .map-pin:nth-of-type(4) { animation-delay: .36s; }\n@keyframes spin { to { transform: rotate(360deg); } } @keyframes pulse { 50% { box-shadow: 0 0 0 8px rgba(120,171,85,.2); transform: scale(1.18); } } @keyframes pinPulse { 50% { filter: brightness(1.15); transform: rotate(-45deg) scale(1.08); } } @keyframes mapSweep { from { opacity: .5; transform: rotate(19deg) translateX(-8px); } to { opacity: .95; transform: rotate(19deg) translateX(8px); } } @keyframes searchStatusIn { from { opacity: 0; transform: translateY(-5px); } to { opacity: 1; transform: translateY(0); } }\n@media (prefers-reduced-motion: reduce) { .button-spinner, .status-loader, .map-is-searching .fake-map::before, .map-is-searching .map-pulse, .map-is-searching .map-pin { animation: none !important; } }\n'''
css.write_text(s)
