from pathlib import Path
p = Path('/home/ubuntu/lumin-candles-store/client/src/pages/Home.tsx')
s = p.read_text()
old = '<div className="tracking-actions"><button onClick={() => toast("تم فتح محادثة تجريبية مع مقدم الخدمة") }><MessageCircle size={16} /> مراسلة</button>'
new = '<div className="tracking-actions"><button onClick={() => setChatOpen((value) => !value)} className={chatOpen ? "chat-active" : ""}><MessageCircle size={16} /> مراسلة {chatMessages.length > 2 && <span className="chat-badge">{chatMessages.length - 2}</span>}</button>'
if old not in s: raise SystemExit('chat button marker not found')
s = s.replace(old, new, 1)
old2 = '''<p className="tracking-note"><ShieldCheck size={13} /> التتبع تجريبي في المعاينة ولا يشارك موقعًا حقيقيًا.</p></div></div>}
'''
new2 = '''{chatOpen && <div className="chat-window"><div className="chat-window-head"><div><strong>محادثة مع مقدم الخدمة</strong><span><i /> متصل الآن</span></div><button onClick={() => setChatOpen(false)} aria-label="إغلاق المحادثة"><X size={15} /></button></div><div className="chat-messages">{chatMessages.map((message, index) => <div key={`${message.from}-${index}`} className={`chat-message ${message.from === "user" ? "mine" : "theirs"}`}><span>{message.text}</span><small>{index === chatMessages.length - 1 ? "الآن" : "منذ لحظات"}</small></div>)}</div><form className="chat-compose" onSubmit={(event) => { event.preventDefault(); sendChatMessage(); }}><input value={chatInput} onChange={(event) => setChatInput(event.target.value)} placeholder="اكتب رسالتك..." aria-label="رسالة لمقدم الخدمة" /><button type="submit" aria-label="إرسال الرسالة"><ArrowLeft size={16} /></button></form></div>}<p className="tracking-note"><ShieldCheck size={13} /> التتبع تجريبي في المعاينة ولا يشارك موقعًا حقيقيًا.</p></div></div>}
'''
if old2 not in s: raise SystemExit('chat panel marker not found')
s = s.replace(old2, new2, 1)
p.write_text(s)
css = Path('/home/ubuntu/lumin-candles-store/client/src/index.css')
s = css.read_text()
s += '''\n.chat-active { background: #eaf5d8 !important; border-color: #afd080 !important; color: #4e7d3b !important; }\n.chat-badge { display: inline-flex; height: 16px; min-width: 16px; align-items: center; justify-content: center; border-radius: 999px; background: #7cab52; color: white; font-size: 8px; }\n.chat-window { margin: 0 25px 16px; overflow: hidden; border: 1px solid #dce8dd; border-radius: 13px; background: #f1f6f1; }\n.chat-window-head { display: flex; align-items: center; justify-content: space-between; border-bottom: 1px solid #dce8dd; background: #fbfdfb; padding: 11px 13px; }\n.chat-window-head strong, .chat-window-head span { display: block; }.chat-window-head strong { color: #365040; font-size: 11px; }.chat-window-head span { margin-top: 3px; color: #78907f; font-size: 8px; }.chat-window-head span i { display: inline-block; height: 5px; width: 5px; margin-left: 3px; border-radius: 999px; background: #79ad5b; }\n.chat-window-head button { color: #80968a; }.chat-messages { display: flex; max-height: 150px; flex-direction: column; gap: 8px; overflow-y: auto; padding: 11px; }.chat-message { display: flex; max-width: 82%; flex-direction: column; gap: 3px; }.chat-message span { border-radius: 11px; padding: 8px 10px; font-size: 10px; line-height: 1.7; }.chat-message small { color: #a0ada4; font-size: 8px; }.chat-message.theirs { align-self: flex-start; }.chat-message.theirs span { border-bottom-right-radius: 3px; background: white; color: #536b5b; }.chat-message.mine { align-self: flex-end; align-items: flex-end; }.chat-message.mine span { border-bottom-left-radius: 3px; background: #dff1bd; color: #3c6035; }.chat-compose { display: flex; gap: 6px; border-top: 1px solid #dce8dd; background: white; padding: 8px; }.chat-compose input { min-width: 0; flex: 1; border: 0; background: transparent; color: #425b4b; font-size: 10px; outline: none; }.chat-compose input::placeholder { color: #a1aea5; }.chat-compose button { display: flex; height: 29px; width: 29px; align-items: center; justify-content: center; border-radius: 8px; background: var(--navy); color: var(--lime); }.chat-compose button:hover { background: #234431; }\n@media (max-width: 640px) { .chat-window { margin-inline: 20px; } }\n'''
css.write_text(s)
