from pathlib import Path
p=Path('/home/ubuntu/lumin-candles-store/client/src/pages/Home.tsx')
s=p.read_text()
s=s.replace('''<button className="dark-button" onClick={() => toast("سيتم فتح تسجيل مقدمي الخدمة في المرحلة التالية")}>سجّل كمقدم خدمة <ArrowLeft size={16} /></button>''','''<button className="dark-button" onClick={() => setProviderModalOpen(true)}>سجّل كمقدم خدمة <ArrowLeft size={16} /></button>''',1)
needle='''      {requestOpen && <div className="modal-backdrop"'''
modal='''      {providerModalOpen && <div className="modal-backdrop" onClick={() => setProviderModalOpen(false)}><div className="request-modal provider-modal" onClick={(event) => event.stopPropagation()}><div className="modal-top"><div><span className="section-label">ملف مقدم الخدمة</span><h2>وثّق خبرتك وابدأ استقبال الطلبات</h2></div><button onClick={() => setProviderModalOpen(false)} className="modal-close" aria-label="إغلاق"><X size={18} /></button></div><p className="modal-preview-note">تظهر هذه البيانات للمنصة فقط، ولا تُعرض للطرف الآخر. سيظهر اسم العرض فقط بعد الاتفاق.</p><form className="provider-form" onSubmit={(event) => { event.preventDefault(); createProviderMutation.mutate({ businessName: providerBusinessName, serviceType: providerServiceType, phone: providerPhone, coverageArea: providerCoverage, commercialRegistrationNumber: providerCrNumber || undefined, operatingCardNumber: providerCardNumber || undefined }, { onSuccess: () => { toast.success("تم حفظ ملفك وإرساله للمراجعة"); setProviderModalOpen(false); }, onError: (error) => toast.error(error.message) }); }}><label>اسم المنشأة أو اسم العرض<input value={providerBusinessName} onChange={(event) => setProviderBusinessName(event.target.value)} placeholder="مثال: نجدة الرياض" required /></label><div className="provider-form-grid"><label>نوع الخدمة<select value={providerServiceType} onChange={(event) => setProviderServiceType(event.target.value)}><option>سطحة وإنقاذ</option><option>صيانة متنقلة</option><option>معدات ثقيلة</option><option>مشاريع ومقاولات</option></select></label><label>منطقة التغطية<input value={providerCoverage} onChange={(event) => setProviderCoverage(event.target.value)} required /></label></div><label>رقم الجوال للتواصل مع المنصة<input dir="ltr" value={providerPhone} onChange={(event) => setProviderPhone(event.target.value)} placeholder="05xxxxxxxx" required /></label><div className="provider-form-grid"><label>السجل التجاري <span>(اختياري)</span><input dir="ltr" value={providerCrNumber} onChange={(event) => setProviderCrNumber(event.target.value)} placeholder="CR-000000" /></label><label>كرت التشغيل <span>(للسطحات والمعدات)</span><input dir="ltr" value={providerCardNumber} onChange={(event) => setProviderCardNumber(event.target.value)} placeholder="OP-000000" /></label></div><button className="request-submit" type="submit" disabled={createProviderMutation.isPending}>{createProviderMutation.isPending ? "جارٍ الحفظ..." : "إرسال الملف للمراجعة"}<ArrowLeft size={17} /></button></form></div></div>}
'''
if needle not in s: raise SystemExit('modal insertion point not found')
s=s.replace(needle,modal+needle,1)
p.write_text(s)
