from pathlib import Path
p = Path('/home/ubuntu/lumin-candles-store/client/src/pages/Home.tsx')
s = p.read_text()
old = '<div className="map-toolbar"><div className="map-location"><span className="map-pulse" /><span>موقعك الحالي</span></div><span className="map-city">الرياض، السعودية</span></div><div className="fake-map">'
new = '''<div className="map-toolbar"><div className="map-location"><span className="map-pulse" /><span>موقعك الحالي</span></div><span className="map-city">الرياض، السعودية</span></div><div className="map-filters"><label><span>نوع الخدمة</span><select value={mapServiceFilter} onChange={(event) => setMapServiceFilter(event.target.value)}><option value="all">كل الخدمات</option>{services.map((service) => <option key={service.id} value={service.id}>{service.title}</option>)}</select></label><label><span>التقييم</span><select value={mapRatingFilter} onChange={(event) => setMapRatingFilter(event.target.value)}><option value="all">كل التقييمات</option><option value="4.8">٤٫٨ فأعلى</option><option value="4.9">٤٫٩ فأعلى</option></select></label><button className="clear-map-filters" onClick={() => { setMapServiceFilter("all"); setMapRatingFilter("all"); }}>مسح</button></div><div className="fake-map">'''
if old not in s: raise SystemExit('toolbar marker not found')
s = s.replace(old, new, 1)
old_pins = '<button className="map-pin pin-one" onClick={() => toast("شركة درب الإنقاذ — ٨ دقائق")}><Truck size={15} /></button><button className="map-pin pin-two" onClick={() => toast("ورشة السريع — ١١ دقيقة")}><Wrench size={15} /></button><button className="map-pin pin-three" onClick={() => toast("مساندة للآليات — ١٦ دقيقة")}><Package size={15} /></button>'
new_pins = '''{(mapServiceFilter === "all" || mapServiceFilter === "tow") && <button className="map-pin pin-one" onClick={() => toast("شركة درب الإنقاذ — ٨ دقائق")}><Truck size={15} /></button>}{(mapServiceFilter === "all" || mapServiceFilter === "mobile") && <button className="map-pin pin-two" onClick={() => toast("ورشة السريع — ١١ دقيقة")}><Wrench size={15} /></button>}{(mapServiceFilter === "all" || mapServiceFilter === "heavy") && <button className="map-pin pin-three" onClick={() => toast("مساندة للآليات — ١٦ دقيقة")}><Package size={15} /></button>}{(mapServiceFilter === "all" || mapServiceFilter === "projects") && <button className="map-pin pin-four" onClick={() => toast("حلول مواقع البناء — ٢٢ دقيقة")}><HardHat size={15} /></button>}'''
if old_pins not in s: raise SystemExit('pins marker not found')
s = s.replace(old_pins, new_pins, 1)
s = s.replace('<span><span className="status-dot" /> ١٢ مقدم خدمة متاح الآن</span>', '<span><span className="status-dot" /> {filteredMapProviders.length} مقدم خدمة مطابق</span>', 1)
p.write_text(s)
css = Path('/home/ubuntu/lumin-candles-store/client/src/index.css')
styles = css.read_text()
styles += '''\n.map-filters { display: flex; align-items: end; gap: 8px; border-top: 1px solid #d8e3d7; background: #f2f7f1; padding: 10px 16px; }\n.map-filters label { display: grid; min-width: 0; flex: 1; gap: 4px; color: #83948a; font-size: 8px; }\n.map-filters select { min-width: 0; border: 1px solid #d7e4d7; border-radius: 7px; background: white; padding: 6px 7px; color: #4b6557; font-size: 9px; outline: none; }\n.map-filters select:focus { border-color: #9dc36e; }\n.clear-map-filters { padding: 6px 5px; color: #6e8b71; font-size: 9px; white-space: nowrap; }\n.clear-map-filters:hover { color: #254d35; }\n.pin-four { top: 67%; left: 38%; background: #68744b; }\n.tone-slate { background: #e1e7e5; color: #263e3a; }\n@media (max-width: 640px) { .map-filters { padding: 9px 11px; } .map-filters select { font-size: 8px; } }\n'''
css.write_text(styles)
